# Generated by Django 4.2 on 2024-05-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RAG_System", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ragmessages",
            name="File",
            field=models.FileField(
                default=None, max_length=300, null=True, upload_to="media//"
            ),
        ),
    ]
