# Generated by Django 4.2 on 2024-05-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RAG_System", "0002_alter_ragmessages_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ragmessages",
            name="File",
            field=models.CharField(max_length=250),
        ),
    ]
